import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import { useTheme } from "next-themes";
import {
  GraduationCap, Bookmark, Map, Code2, Users, CalendarCheck,
  ArrowRight, Sun, Moon, Sparkles, Shield, Zap,
} from "lucide-react";

const features = [
  { icon: Bookmark, title: "Resource Vault", desc: "Save links, code snippets & documents in one place. Never lose an important resource again." },
  { icon: Map, title: "AI Roadmaps", desc: "Get personalized step-by-step learning paths generated by AI for any goal." },
  { icon: Code2, title: "Testpad", desc: "Practice coding in a real exam-like environment with AI-generated problems & test cases." },
  { icon: Users, title: "Community", desc: "Raise issues, share complaints, and upvote what matters to your campus." },
  { icon: CalendarCheck, title: "Leave Manager", desc: "Calculate exactly how many lectures you can skip and still maintain attendance." },
  { icon: Shield, title: "All Offline-Ready", desc: "Your data stays in your browser. No sign-up needed, start using instantly." },
];

const Landing = () => {
  const { theme, setTheme } = useTheme();

  return (
    <div className="min-h-screen relative overflow-hidden">
      {/* Background */}
      <div className="fixed inset-0 -z-10 overflow-hidden">
        <div className="absolute -top-[30%] -right-[15%] w-[700px] h-[700px] rounded-full bg-primary/5 blur-[140px]" />
        <div className="absolute -bottom-[20%] -left-[10%] w-[500px] h-[500px] rounded-full bg-primary/8 blur-[120px]" />
        <div className="absolute top-[50%] left-[40%] w-[350px] h-[350px] rounded-full bg-accent/30 blur-[100px]" />
      </div>

      {/* Navbar */}
      <nav className="fixed top-0 left-0 right-0 z-50 glass">
        <div className="max-w-6xl mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="h-9 w-9 rounded-xl bg-primary/10 flex items-center justify-center">
              <GraduationCap className="h-5 w-5 text-primary" />
            </div>
            <span className="text-xl font-bold bg-gradient-to-r from-primary to-primary/60 bg-clip-text text-transparent">Saarthi</span>
          </div>
          <div className="flex items-center gap-3">
            <button onClick={() => setTheme(theme === "dark" ? "light" : "dark")} className="p-2.5 rounded-xl hover:bg-muted/50 transition-colors text-muted-foreground">
              {theme === "dark" ? <Sun className="h-4 w-4" /> : <Moon className="h-4 w-4" />}
            </button>
            <Link to="/dashboard" className="flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-medium bg-primary text-primary-foreground hover:bg-primary/90 transition-colors">
              Open App <ArrowRight className="h-4 w-4" />
            </Link>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="pt-32 pb-20 px-6">
        <div className="max-w-4xl mx-auto text-center">
          <motion.div initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }}>
            <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full glass-subtle text-xs font-medium text-muted-foreground mb-8">
              <Sparkles className="h-3.5 w-3.5 text-primary" /> Your college companion
            </div>
            <h1 className="text-5xl md:text-7xl font-bold tracking-tight leading-[1.1]">
              Everything you need.<br />
              <span className="bg-gradient-to-r from-primary via-primary/80 to-primary/50 bg-clip-text text-transparent">One tab open.</span>
            </h1>
            <p className="mt-6 text-lg md:text-xl text-muted-foreground max-w-2xl mx-auto leading-relaxed">
              Saarthi is the all-in-one student companion — save resources, generate roadmaps, practice coding, manage attendance, and more.
            </p>
          </motion.div>
          <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3, duration: 0.5 }} className="mt-10 flex flex-col sm:flex-row items-center justify-center gap-4">
            <Link to="/dashboard" className="flex items-center gap-2 px-8 py-3.5 rounded-2xl text-sm font-semibold bg-primary text-primary-foreground hover:bg-primary/90 transition-all hover:scale-[1.02] shadow-lg shadow-primary/20">
              Get Started — It's Free <ArrowRight className="h-4 w-4" />
            </Link>
            <a href="#features" className="flex items-center gap-2 px-8 py-3.5 rounded-2xl text-sm font-medium glass-subtle hover:scale-[1.02] transition-all text-foreground">See Features</a>
          </motion.div>
          <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.5, duration: 0.5 }} className="mt-16 grid grid-cols-3 gap-6 max-w-lg mx-auto">
            {[{ value: "5+", label: "Tools" }, { value: "0", label: "Sign-ups needed" }, { value: "∞", label: "Potential" }].map((stat) => (
              <div key={stat.label} className="text-center">
                <p className="text-2xl md:text-3xl font-bold text-primary">{stat.value}</p>
                <p className="text-xs text-muted-foreground mt-1">{stat.label}</p>
              </div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* Features */}
      <section id="features" className="py-20 px-6">
        <div className="max-w-6xl mx-auto">
          <motion.div initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="text-center mb-14">
            <h2 className="text-3xl md:text-4xl font-bold tracking-tight">Built for students, <span className="text-primary">by students</span></h2>
            <p className="text-muted-foreground mt-3 max-w-xl mx-auto">Every tool you wish you had during college — all in one beautifully designed app.</p>
          </motion.div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {features.map((feature, i) => (
              <motion.div key={feature.title} initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * 0.08 }}>
                <div className="glass-subtle rounded-2xl p-6 h-full hover:scale-[1.02] transition-transform duration-200">
                  <div className="h-11 w-11 rounded-xl bg-primary/10 flex items-center justify-center mb-4">
                    <feature.icon className="h-5 w-5 text-primary" />
                  </div>
                  <h3 className="font-semibold text-base">{feature.title}</h3>
                  <p className="text-sm text-muted-foreground mt-2 leading-relaxed">{feature.desc}</p>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-20 px-6">
        <div className="max-w-3xl mx-auto">
          <motion.div initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="glass rounded-3xl p-10 md:p-14 text-center">
            <Zap className="h-8 w-8 text-primary mx-auto mb-4" />
            <h2 className="text-3xl md:text-4xl font-bold tracking-tight">Ready to simplify college?</h2>
            <p className="text-muted-foreground mt-3 max-w-lg mx-auto">No sign-up. No downloads. Just open Saarthi and start being productive.</p>
            <Link to="/dashboard" className="inline-flex items-center gap-2 mt-8 px-8 py-3.5 rounded-2xl text-sm font-semibold bg-primary text-primary-foreground hover:bg-primary/90 transition-all hover:scale-[1.02] shadow-lg shadow-primary/20">
              Launch Saarthi <ArrowRight className="h-4 w-4" />
            </Link>
          </motion.div>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-8 px-6 border-t border-border/50">
        <div className="max-w-6xl mx-auto flex items-center justify-between text-xs text-muted-foreground">
          <div className="flex items-center gap-2"><GraduationCap className="h-4 w-4 text-primary" /><span className="font-medium">Saarthi</span></div>
          <p>Built with ❤️ for students</p>
        </div>
      </footer>
    </div>
  );
};

export default Landing;
